# Generated by Django 3.1.7 on 2021-03-22 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.link.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "uuid",
                    models.CharField(
                        default=apps.link.models.get_short_link_uuid,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Uniq ID",
                    ),
                ),
                ("original_link", models.URLField(max_length=1024, verbose_name="Link"),),
                (
                    "visited_count",
                    models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="Visited count"),
                ),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="User",
                    ),
                ),
            ],
            options={"ordering": ["user", "created"],},
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID",),),
                ("visitor_data", models.JSONField(blank=True, default=dict, null=True, verbose_name="Visitor data"),),
                ("real_ip", models.GenericIPAddressField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("link", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="link.link"),),
            ],
            options={"ordering": ["created"],},
        ),
    ]
