# Generated by Django 3.1.7 on 2021-03-21 10:39

import apps.link.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['user', 'created']},
        ),
        migrations.RenameField(
            model_name='link',
            old_name='link',
            new_name='original_link',
        ),
        migrations.RemoveField(
            model_name='link',
            name='id',
        ),
        migrations.RemoveField(
            model_name='link',
            name='shortened',
        ),
        migrations.RemoveField(
            model_name='link',
            name='uses',
        ),
        migrations.AddField(
            model_name='link',
            name='uuid',
            field=models.CharField(default=apps.link.models.get_short_link_uuid, max_length=8, primary_key=True, serialize=False, verbose_name='Uniq ID'),
        ),
        migrations.AlterField(
            model_name='link',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='Visitor data')),
                ('count', models.IntegerField(default=0, verbose_name='Visited count')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='link.link')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
