# Generated by Django 3.1.7 on 2021-03-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_auto_20210321_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='visited_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Visited count'),
        ),
    ]
