# Generated by Django 3.1.7 on 2021-03-21 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0003_link_visited_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='count',
        ),
    ]
