# Generated by Django 3.1.7 on 2021-03-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0004_remove_visit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='real_ip',
            field=models.GenericIPAddressField(default='1.1.1.1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='visited_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Visited count'),
        ),
    ]
